[build]
builder = "DOCKERFILE"

[deploy]
startCommand = "python manage.py collectstatic --noinput && python manage.py migrate && gunicorn multitask_backend.wsgi --bind 0.0.0.0:$PORT"
healthCheckPath = "/"
restartPolicyType = "ON_FAILURE"
maxRetries = 10
